title: <TITLE>
port: <PORT>
redis:
  host: ipepdvcompute1.ipe.kit.edu
  port: 6379
tabs:
  config: true
  main: true
  notebook: http://ipepdvcompute1.ipe.kit.edu:8000
timer:
  client: 1000
  plugins: adei
  retention: 86400000
  server: 60000
